### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by Taotaoxu** [CrazyStoneonRoad/TGRS-HRRSD-Dataset#2]
Thanks for your dataset. 
Can you provide the **Benchmark** based on the classic and latest detectors ? 
Such as the Faster R-CNN, RetinaNet, SSD, YOLO, Anchor-free family, etc.

**Comment by CrazyStoneonRoad** [comment]
Thank you very much for your question, which is an important problem and has been ignored for a long time. The benchmark will be available soon. Thanks again for your contribution.

**Comment by CrazyStoneonRoad** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Question has been answered in the Issue Page.
            
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1153463027
                            
                    
                        
                            
                                    1153463027@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 8/19/2020 20:32，xtao<notifications@github.com> wrote： 



Thanks for your dataset.
Can you provide the Benchmark based on the classical and latest detectors ?
Such as the Faster R-CNN, RetinaNet, SSD, YOLO, Anchor-free family, etc.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
